version: "2"
services:
  patient-service:
    build: patient-service/
    container_name: patient-service
    depends_on:
      - api-gateway
      - eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8082:8082
  doctor-service:
    build: doctor-service/
    container_name: doctor-service
    depends_on:
      - api-gateway
      - eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8085:8085
  volunteer-service:
    build: volunteer-service/
    container_name: volunteer-service
    depends_on:
      - api-gateway
      - eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8081:8081
  medicine-service:
    build: medicine-service/
    container_name: medicine-service
    depends_on:
      - api-gateway
      - eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8083:8083
  email-service:
    build: email-service/
    container_name: email-service
    depends_on:
      - api-gateway
      - eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8084:8084
  consultation-patient-service:
    build: consultation-patient-service/
    container_name: consultation-patient-service
    depends_on:
      - api-gateway
      - eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8087:8087