eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8086

spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*,*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
      routes:
        - id: register-service
          uri: http://localhost:8080/
          predicates:
            - Path=/reg/**

        - id: volunteer-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/**

        - id: patient-service
          uri: http://localhost:8082/
          predicates:
            - Path=/patient/**

        - id: medicine-service
          uri: http://localhost:8083/
          predicates:
            - Path=/meds/**

        - id: email-service
          uri: http://localhost:8084/
          predicates:
            - Path=/email/**

        - id: doctor-service
          uri: http://localhost:8085/
          predicates:
            - Path=/doctor/**

        - id: consultation-patient-service
          uri: http://localhost:8087/
          predicates:
            - Path=/consult/**

        - id: product-webapp
          uri: http://localhost:8099/
          predicates:
            - Path=/**

