#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/projectwork
#    username: root
#    password: Sarath@2000
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update

#Mongo Config

spring:
  application:
    name: Consultation-Patient-Service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Patient-Symptoms


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
